### PR TITLE
Preliminary code comments have been added for Zircon-syscalls

### PR DESCRIPTION
**Pull request by iLFTH**
Added simple description for Zircon system calls.
Cargo doc updated :zCore/target/doc/zircon_syscall/struct.Syscall.html

### CODE REVIEW

**Comment by wangrunji0408** [comment]
Why closed?

**Comment by iLFTH** [comment]
Sorry, the automatic check didn't pass. Because I haven't run “cargo fmt” to format the code before this  “pull request”.          I will resubmit it tomorrow.

**Comment by wangrunji0408** [comment]
You can commit to and push this branch directly. The PR will trace the update.

**Review by wangrunji0408 — CHANGES_REQUESTED** [review]

**Review by wangrunji0408 — APPROVED** [review]
Good job!

**Pull request merged**
