### PR TITLE
Mark context run

### PR DESCRIPTION
**Pull request by GCYYfun**
# Marking the very important code "context run"😨

### CODE REVIEW

**Comment by wangrunji0408** [comment]
Cherry-pick b124230 to the master?

**Comment by GCYYfun** [comment]
> Cherry-pick [b124230](https://github.com/rcore-os/zCore/commit/b124230c6f969b4c141e0cc9babfd751220c71a2) to the master?

Scary Branches.
Seal！！！

**Comment by wangrunji0408** [comment]
Replaced by #144

**Comment by GCYYfun** [comment]
Fixed this horrible, though deprecated, branch with 'cherry-pick'.

A very nice command.

**Pull request closed without merging**
