### PR TITLE
Try to fix test `object::tests::wait_many`

### LINKED ISSUE #107: The unit test object::tests::wait_many occasionally failed
This is annoying when the CI fails because of this unit test. Better to get it fixed.

### PR DESCRIPTION
**Pull request by xxchan**
Try to resolve https://github.com/rcore-os/zCore/issues/107

`object::tests::wait_many` occasionally failed, e.g., https://github.com/rcore-os/zCore/runs/885395893.

The failure is:
```
---- object::tests::wait_many stdout ----
thread 'object::tests::wait_many' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`', zircon-object/src/object/mod.rs:575:9
```
zircon-object/src/object/mod.rs:575 is
```Rust
assert_eq!(flag.load(Ordering::SeqCst), 0);
```

Actually I don't fully understand the useage of `flag`. I guess it is just used to indicate the program execution sequence. And I think the order of line 575 `assert_eq!(flag.load(Ordering::SeqCst), 0);` and the line 565 `flag.store(1, Ordering::SeqCst);` is uncertain, so the test sometimes fails. I think adding a `sleep` can help ensure the execution order.

btw, I still have some questions
- Why test `wait_many` fails, but `wait` doesn't?
- I can't reproduce the test failure on my mac.
- On my mac `wait_many` sometimes gets stuck (frequency ≈ 1 in 10). I didn't figure out the cause. Howerver, this `sleep` also fixed this, which surprised me……

image

### CODE REVIEW

**Comment by wangrunji0408** [comment]
In fact test case `wait` will also fail occasionally :(
I think the source of uncertainty comes from `sleep`. The sleep time is not enough to wait for the main thread to complete its assertion.
Maybe we should use [`Barrier`](https://docs.rs/async-std/1.6.2/async_std/sync/struct.Barrier.html) to replace `sleep` and `flag`.
What do you think?

**Comment by xxchan** [comment]
> I think the source of uncertainty comes from `sleep`. The sleep time is not enough to wait for the main thread to complete its assertion.

See the original code below. It is expected that B comes before A, but sometimes A comes before B which causes the test failure in https://github.com/rcore-os/zCore/runs/885395893. The order of A and B is uncertain, which I think has nothing to do with `sleep`……So I tried to solve this by adding a `sleep` before A. But I agree there is still a possibility that sleep time is not enough.(I don't know whether there exist other failures caused by `sleep`)
```rust
async fn wait_many() {
    let objs = [DummyObject::new(), DummyObject::new()];
    let flag = Arc::new(AtomicU8::new(0));

    async_std::task::spawn({
        let objs = objs.clone();
        let flag = flag.clone();
        async move {
            // A
            flag.store(1, Ordering::SeqCst);
            objs[0].signal_set(Signal::READABLE);
            async_std::task::sleep(Duration::from_millis(10)).await;

            // ...
        }
    });
    let obj0: Arc<dyn KernelObject> = objs[0].clone();
    let obj1: Arc<dyn KernelObject> = objs[1].clone();
    // B
    assert_eq!(flag.load(Ordering::SeqCst), 0);
    // ...
}
```

> Maybe we should use `Barrier` to replace sleep and flag.

Let me take a look :)

**Comment by xxchan** [comment]
btw, why `wait_many` sometimes gets stuck (forever) still can't be explained……

**Comment by xxchan** [comment]
Well, let me tell my understanding of the test case first:

There are two `wait`s and two `signal_set`s. The expected sequence is: 
1. wait READABLE 
2. set READABLE
3. wait WRITABLE
4. set WRITABLE

`flag` does not affect this order, but only checks whether it is achieved. The orginal `sleep` is used to help ensure 3 happens before 4.

My idea about improvements:

I think adding a `sleep` before 2 can help ensure 1 happens before 2 (But should sleep for enough time?).

I think using other sync tools like `Barrier` or writing a spin lock with `flag` cannot necessarily guarantee `wait` before `signal_set`, neither.

**Comment by wangrunji0408** [comment]
You are right. There's no way other than sleep (for enough time) to make sure `wait` happens before `set`. And I think it's not necessary, `set -> wait` is also a reasonable case.

The original purpose of `flag` is to synchronize 2 threads and prevent this case:
```
Thread 1        Thread 2
wait A
                set A
                set B
get AB != A
```

Now I realized that it's not a good design, a barrier can better solve this problem:

```
Thread 1        Thread 2
wait A          sleep (long)
                set A
get A
----------Barrier----------
                sleep (short)
                set B
wait B
get AB
```

As for the stuck... I think there maybe a lost wakeup problem:
https://github.com/rcore-os/zCore/blob/9900bf1c5f1f5c92b190a9ac5e1ab62c62de9570/zircon-object/src/object/mod.rs#L297-L321

We don't keep the lock between L301-L306. So if someone asserts the signal during this period, the callback will not be called and the wakeup will be lost. A possible solution is checking the signal in `add_signal_callback()`.

**Comment by xxchan** [comment]
I agree that `set -> wait` is also a reasonable case, but it may be better to have at lease one `wait -> set` case to test the `Pending` case and the wakeup logic? 

So the changes I made:
- **The lost wakeup problem**: 
  Check the callback immediately in `add_signal_callback()`. I don't know if it is the best solution. It seems that Zircon 
doesn't do so, but it acquires lock outside `wait_state_observer.Begin()`, which adds a observer.
- **The failed test problem**: 
  - Remove the confusing `flag`s. 
  - Use a `sleep` to ensure `wait A -> set A` (not sure whether 20ms is long enough), but do not restrict the order of `wait B -> set B`.
  - Use a `Barrier` to avoid `set A -> set B -> get AB`.
    Although `Barrier` is unstable, but using it in tests (dev-dependencies) may not hurt?

**Review by wangrunji0408 — APPROVED** [review]
Looks good!

**Pull request merged**
